memodir = "~/memo"
editor = "nvim"
column = 20
width = 0
selectcmd = "fzf"
grepcmd = "rg -nH ${PATTERN} ${FILES}"
memotemplate = ""
assetsdir = "."
pluginsdir = "~/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
