typeset -g POWERLEVEL9K_MODE=ascii
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(status dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(aws gcloud)
typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='> '
typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_OK_PIPELINE=false
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER='FAIL'

typeset -g POWERLEVEL9K_DIR_FOREGROUND=33
typeset -g POWERLEVEL9K_DIR_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=''
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=178
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=''
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=196
typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=''

typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform|pulumi|cdk'
typeset -g POWERLEVEL9K_AWS_FOREGROUND=208
typeset -g POWERLEVEL9K_AWS_BACKGROUND=''

typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gsutil|bq'
typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=39
typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=''
