[directory]
truncation_length = 5
truncate_to_repo = true

[memory_usage]
disabled = true
threshold = -1

[docker_context]
disabled = true

[character]
success_symbol="🐰"
error_symbol="🐰"
vimcmd_symbol="🐰"
vimcmd_replace_one_symbol="🐰"
vimcmd_replace_symbol="🐰"
vimcmd_visual_symbol="🐰"

[battery]
disabled=true

[git_branch]
symbol = ''

[aws]
format = 'on [$symbol$profile]($style) '
style = 'bold blue'
symbol = '🅰 '
[aws.profile_aliases]
Enterprise_Naming_Scheme-voidstars = 'void**'

[bun]
disabled = true
format = "via [$symbol]($style)"

[buf]
disabled = true
format = "via [$symbol]($style)"

[cmake]
disabled = true
format = "via [$symbol]($style)"

[cobol]
disabled = true
format = "via [$symbol]($style)"

[crystal]
disabled = true
format = "via [$symbol]($style)"

[daml]
disabled = true
format = "via [$symbol]($style)"

[dart]
disabled = true
format = "via [$symbol]($style)"

[deno]
disabled = true
format = "via [$symbol]($style)"

[dotnet]
disabled = true
format = "[$symbol(🎯 $tfm )]($style)"

[elixir]
disabled = true
format = 'via [$symbol]($style)'

[elm]
disabled = true
format = 'via [$symbol]($style)'

[erlang]
disabled = true
format = 'via [$symbol]($style)'

[fennel]
disabled = true
format = 'via [$symbol]($style)'

[gleam]
disabled = true
format = 'via [$symbol]($style)'

[golang]
disabled = true
format = 'via [$symbol]($style)'

[gradle]
disabled = true
format = 'via [$symbol]($style)'

[haxe]
disabled = true
format = 'via [$symbol]($style)'

[helm]
disabled = true
format = 'via [$symbol]($style)'

[java]
disabled = true
format = 'via [$symbol]($style)'

[julia]
disabled = true
format = 'via [$symbol]($style)'

[kotlin]
disabled = true
format = 'via [$symbol]($style)'

[lua]
disabled = true
format = 'via [$symbol]($style)'

[meson]
disabled = true
format = 'via [$symbol]($style)'

[nim]
disabled = true
format = 'via [$symbol]($style)'

[nodejs]
disabled = true
format = 'via [$symbol]($style)'

[ocaml]
disabled = true
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
disabled = true
format = 'via [$symbol]($style)'

[perl]
disabled = true
format = 'via [$symbol]($style)'

[php]
disabled = true
format = 'via [$symbol]($style)'

[pulumi]
disabled = true
format = 'via [$symbol$stack]($style)'

[purescript]
disabled = true
format = 'via [$symbol]($style)'

[python]
disabled = true
format = 'via [$symbol]($style)'

[quarto]
disabled = true
format = 'via [$symbol]($style)'

[raku]
disabled = true
format = 'via [$symbol]($style)'

[red]
disabled = true
format = 'via [$symbol]($style)'

[rlang]
disabled = true
format = 'via [$symbol]($style)'

[ruby]
disabled = true
format = 'via [$symbol]($style)'

[rust]
disabled = true
format = 'via [$symbol]($style)'

[solidity]
disabled = true
format = 'via [$symbol]($style)'

[typst]
disabled = true
format = 'via [$symbol]($style)'

[swift]
disabled = true
format = 'via [$symbol]($style)'

[vagrant]
disabled = true
format = 'via [$symbol]($style)'

[vlang]
disabled = true
format = 'via [$symbol]($style)'

[zig]
disabled = true
format = 'via [$symbol]($style)'

