[directory]
truncation_length = 100
truncate_to_repo = false

[memory_usage]
disabled = false
threshold = -1
style = "bold dimmed blue"

[docker_context]
disabled = true

[character]
success_symbol="🦊"
error_symbol="🦊"
vimcmd_symbol="🦊"
vimcmd_replace_one_symbol="🦊"
vimcmd_replace_symbol="🦊"
vimcmd_visual_symbol="🦊"
